name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
concurrency:
  group: pipeline-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    env:
      WOTR_PATH: ../../libs
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Build/Test
        run: dotnet test ./src --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"
      - name: Combine Coverage Reports
        if: always()
        uses: danielpalme/ReportGenerator-GitHub-Action@v5.4.10
        with:
          reports: "**/*.cobertura.xml"
          targetdir: "${{ github.workspace }}"
          reporttypes: "Cobertura"
          verbosity: "Info"
          title: "Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          customSettings: "" # https://github.com/danielpalme/ReportGenerator/wiki/Settings.
          toolpath: "reportgeneratortool"
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "${{ github.workspace }}/**/*.trx"
          retention-days: 5
      - name: Upload Combined Coverage XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}/Cobertura.xml
          retention-days: 5
