name: build

on:
  workflow_dispatch:
  #  push:
  #    branches: [ "main" ]
  pull_request:
    branches: ["main"]
concurrency:
  group: pipeline-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    env:
      WOTR_PATH: ../../libs
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: build/test
        run: dotnet test ./src --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"
      - name: Combine Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@v5.4.10
        with:
          reports: "**/*.cobertura.xml"
          targetdir: "${{ github.workspace }}"
          reporttypes: "Cobertura"
          verbosity: "Info"
          title: "Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          customSettings: "" # https://github.com/danielpalme/ReportGenerator/wiki/Settings.
          toolpath: "reportgeneratortool"
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "${{ github.workspace }}/**/*.trx"
          retention-days: 5
      - name: Upload Combined Coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}/Cobertura.xml
          retention-days: 5

  test-reporter:
    needs: [build]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Download Combined Coverage XML
        uses: actions/download-artifact@v4
        with:
          name: coverage
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results
      - name: Publish Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "Cobertura.xml"
          badge: true
          fail_below_min: false # just informative for now
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "10 30"
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.20.0
        if: always()
        with:
          files: "${{ github.workspace }}/**/*.trx"
