name: build

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  pull-requests: write
  checks: write
  contents: read
  issues: read
  actions: read

jobs:
  test-reporter:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Download Combined Coverage XML
        uses: actions/download-artifact@v4
        with:
          name: coverage
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results
      - name: Publish Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "Cobertura.xml"
          badge: true
          fail_below_min: false # just informative for now
          format: markdown
          hide_branch_rate: true
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "10 30"
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"
          job_summary: false
          check_run: false
      - uses: dorny/test-reporter@v2
        with:
          name: Test Results
          path: "**/*.trx"
          artifact: test-results
          reporter: dotnet-trx
          fail-on-error: false
